<?php
include_once('AddAssets.php');
include_once('AdminAdd.php');
include_once('Assets.php');
include_once('Category.php');
include_once('Check.php');
include_once('Common.php');
include_once('Language.php');
include_once('Location.php');
include_once('PaginatedData.php');
include_once('Path.php');
include_once('Update_password.php');
include_once('UpdateProfile.php');
include_once('UserDetail.php');
include_once('UserDirectory.php');
include_once('UpdateAssets.php');
include_once('DeleteAssets.php');
//include_once('FileUpload.php');
?>